root_node_inputs:
  - [3692.94,1071.6] #[147717.5, 4286.4]
  
constraint:
  auxiliary: 'None'

node_aux: None

feas_thresh: 0.1

memory: false

model_version: null

integration:
  scheme: tsit5  # dopri8
  step_size_controller: pid
  t0: 0
  tf: 1
  dt0: 1.0e-1
  max_steps: 10000